/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ISvgDanmakuBottomOff: typeof import('~icons/svg/danmaku-bottom-off')['default']
    ISvgDanmakuBottomOn: typeof import('~icons/svg/danmaku-bottom-on')['default']
    ISvgDanmakuColorOff: typeof import('~icons/svg/danmaku-color-off')['default']
    ISvgDanmakuColorOn: typeof import('~icons/svg/danmaku-color-on')['default']
    ISvgDanmakuMoveOff: typeof import('~icons/svg/danmaku-move-off')['default']
    ISvgDanmakuMoveOn: typeof import('~icons/svg/danmaku-move-on')['default']
    ISvgDanmakuOff: typeof import('~icons/svg/danmaku-off')['default']
    ISvgDanmakuOn: typeof import('~icons/svg/danmaku-on')['default']
    ISvgDanmakuSetting: typeof import('~icons/svg/danmaku-setting')['default']
    ISvgDanmakuTopOff: typeof import('~icons/svg/danmaku-top-off')['default']
    ISvgDanmakuTopOn: typeof import('~icons/svg/danmaku-top-on')['default']
    ISvgFullscreenEnter: typeof import('~icons/svg/fullscreen-enter')['default']
    ISvgFullscreenExit: typeof import('~icons/svg/fullscreen-exit')['default']
    ISvgLoading: typeof import('~icons/svg/loading')['default']
    ISvgMute: typeof import('~icons/svg/mute')['default']
    ISvgPause: typeof import('~icons/svg/pause')['default']
    ISvgPicInPicEnter: typeof import('~icons/svg/pic-in-pic-enter')['default']
    ISvgPicInPicExit: typeof import('~icons/svg/pic-in-pic-exit')['default']
    ISvgPlay: typeof import('~icons/svg/play')['default']
    ISvgProcess: typeof import('~icons/svg/process')['default']
    ISvgTextColor: typeof import('~icons/svg/text-color')['default']
    ISvgVolume: typeof import('~icons/svg/volume')['default']
  }
}
